version: '3'

services:
  django_backend:
    build: ./server
    container_name: ai_phishing_django
    volumes:
      - ./server:/code
      - db_data:/code/db.sqlite3
    ports:
      - "8001:8000"
    restart: always

volumes:
  db_data: