# Generated by Django 5.1.1 on 2024-10-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='interest',
            field=models.CharField(choices=[('technology', 'Technology'), ('sports', 'Sports'), ('music', 'Music'), ('art', 'Art')], default='technology', max_length=50),
        ),
        migrations.AddField(
            model_name='reg',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
