# Generated by Django 5.1.3 on 2024-12-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'Normal User'), ('advertiser', 'Advertiser'), ('admin', 'Admin')], default='normal', max_length=20),
        ),
    ]
