# Generated by Django 5.1.3 on 2025-01-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image', models.ImageField(help_text='Upload the image for the advertisement.', upload_to='advertisements/', verbose_name='Advertisement Image')),
                ('title', models.CharField(help_text='Enter the title of the advertisement.', max_length=255, verbose_name='Title')),
                ('link', models.URLField(help_text='Enter the URL or link associated with the advertisement.', max_length=500, verbose_name='Link or URL')),
                ('start_date', models.DateField(help_text='Select the start date for the advertisement.', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Select the end date for the advertisement.', verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
