# Generated by Django 5.1.3 on 2025-01-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.CharField(help_text='Prediction result from the ML model (safe/unsafe).', max_length=10, verbose_name='Prediction')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='Analyzed At')),
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='accounts.advertisement')),
            ],
            options={
                'verbose_name': 'Advertisement Analysis',
                'verbose_name_plural': 'Advertisement Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
